### ISSUE TITLE
Unused mods not spelt correctly

### ISSUE THREAD

**Issue by DragoSMPog** [StowMarines/StowMarines_Interface#6]
Version: 1.0.8 Beta

Bug Details: ![image](https://user-images.githubusercontent.com/85490210/121002303-de15f400-c794-11eb-9d26-09867e1d9603.png)
It says unsued instead of unused, and I don't wish to sue a mod

**Comment by SM-BJS** [comment]
Fixed, will be released in 1.0.9 Beta, thanks!
